//checkout from gitlab project
node {

    //env setting below

    env.PATH = "/var/jenkins_home/k8s:/var/jenkins_home/docker:/usr/bin:/bin:/var/jenkins_home/jdk1.8.0_101/bin:/var/jenkins_home/node/bin:/var/jenkins_home/maven/bin:/var/jenkins_home/groovy/bin:${env.PATH}"
    env.M2_HOME = "/var/jenkins_home/maven"
	env.DOCKER_HOST = "tcp://1.1.1.1:8080"
	env.http_proxy = "http://1.1.1.1:10029"
	//env.no_proxy = "1.1.1.1,1.*.*.*"


    //checkout from gitlab project
    stage('checkout') {
        checkout scm
    }

    env.http_proxy = "http://1.1.1.1:10029"
    env.no_proxy = "1.1.1.1,1.*.*.*"


    //stage is build setp

    stage('check tools') {
        sh "git config --global http.proxy http://1.1.1.1:10029" 
    }

    stage('clean') {
        sh "mvn clean"
    }


     stage('packaging') {
         sh "mvn package -Pprod,zipkin,prometheus,IDE,graphite -DskipTests "
     }

    stage('Build&Push Docker Image') {
        sh "mvn docker:build"
        sh "mvn docker:push"
    }

    stage('Kubernetes RollingUpdate') {
        sh "echo #############triger kubernetes update application #############"
        sh "kubectl --server=99.99.99.99:8080 set image deployment/service service=99.99.99.99:5000/xxx-xxx-sxxxx:v1.1.1"
    }
}
